### ISSUE TITLE
Implement Naive Bayes [DEV SPRINT 7/18]

### ISSUE THREAD

**Issue by markroxor** [markroxor/fromscratchtoml#27]
The first three links on google are the best
https://www.geeksforgeeks.org/naive-bayes-classifiers/
https://www.analyticsvidhya.com/blog/2017/09/naive-bayes-explained/
https://machinelearningmastery.com/naive-bayes-for-machine-learning/

**Comment by mohdkashif93** [comment]
Is it okay if I start working on this issue ?

**Comment by markroxor** [comment]
@mohdkashif93 you can start working on gaussian naive bayes.
