### ISSUE TITLE
Recurrent neural network

### ISSUE THREAD

**Issue by markroxor** [markroxor/fromscratchtoml#48]
http://willwolf.io/2016/10/18/recurrent-neural-network-gradients-and-lessons-learned-therein/
http://www.wildml.com/2015/09/recurrent-neural-networks-tutorial-part-1-introduction-to-rnns/

**Comment by souravsingh** [comment]
Let me look into this

**Comment by markroxor** [comment]
@souravsingh This was part of the dev-sprint, the code is in place in the `rnn` branch. I have pushed most of  the code, some minor fixes are introduced by @Saisuchith in #52.

So don't worry about it.

**Comment by markroxor** [comment]
Along with writing a notebook with working examples. Yes.
